### ISSUE TITLE
Update prow webhook

### ISSUE THREAD

**Issue by fejta** [GoogleCloudPlatform/k8s-cloud-provider#35]
Please set this from https://prow.gflocks.com/hook to http://130.211.32.159/hook, thanks!
An admin needs to go to https://github.com/GoogleCloudPlatform/k8s-cloud-provider/settings/hooks and click the edit button

Prow will not respond to any changes in this repo until this occurs

/cc @bowei

**Comment by bowei** [comment]
Done
